"""Update database schema

Revision ID: a8e28e979228
Revises: 
Create Date: 2025-05-06 21:18:27.633673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8e28e979228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('two_fa_secret', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('is_2fa_enabled')
        batch_op.drop_column('two_fa_secret')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
